package com.example.ui.localization

import androidx.compose.ui.unit.LayoutDirection

enum class AppLanguage {
    ENGLISH, ARABIC, FRENCH
}

object Localizer {
    fun getLayoutDirection(language: AppLanguage): LayoutDirection {
        return if (language == AppLanguage.ARABIC) LayoutDirection.Rtl else LayoutDirection.Ltr
    }

    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_name" to "Karaoke Studio",
            "search_hint" to "Search songs, artists, categories...",
            "sing" to "Sing",
            "recordings" to "Recordings",
            "favorites" to "Favorites",
            "profile" to "Profile",
            "admin" to "Admin Panel",
            "login" to "Log In",
            "register" to "Register",
            "username" to "Username",
            "password" to "Password",
            "email" to "Email Address",
            "no_account" to "Don't have an account? Sign Up",
            "have_account" to "Already have an account? Log In",
            "effects" to "Audio Effects",
            "vocal_removal" to "Vocal Cut (AI simulation)",
            "echo" to "Echo Delay",
            "reverb" to "Reverb Intensity",
            "bass_boost" to "Bass Boost",
            "mic_gain" to "Microphone Gain",
            "score" to "Singing Score",
            "pitch_meter" to "Live Pitch Alignment",
            "play" to "Play",
            "pause" to "Pause",
            "speed" to "Speed Control",
            "pitch" to "Pitch Adjustment (Key)",
            "save_recording" to "Save Vocal Mix",
            "share" to "Share Vocal",
            "xp" to "Vocal XP",
            "level" to "Vocalist Level",
            "achievements" to "Achievements",
            "badges" to "Badges",
            "rank" to "Singer Rank",
            "rank_bronze" to "Bronze Vocalist",
            "rank_silver" to "Silver Vocalist",
            "rank_gold" to "Gold Star",
            "rank_platinum" to "Platinum Artist",
            "rank_legend" to "Karaoke Legend",
            "add_song" to "Add Custom Song",
            "song_title" to "Song Title",
            "artist" to "Artist Name",
            "category" to "Category / Genre",
            "lyrics_lrc" to "Synchronized Lyrics (LRC Format)",
            "lyrics_placeholder" to "[00:05.10]Hello world lyric line\n[00:10.50]Next line of karaoke lyrics",
            "save" to "Save Song",
            "history" to "Singing History",
            "syncing" to "Backing up to Cloud...",
            "vocal_vol" to "Vocal Volume",
            "music_vol" to "Instrumental Volume",
            "perfect" to "Perfect! 🔥",
            "great" to "Great! ✨",
            "good" to "Good! 👍",
            "keep_it_up" to "Keep it up! 🎤",
            "tap_to_sing" to "Tap to Sing Now",
            "settings" to "Settings",
            "logout" to "Log Out",
            "ranking" to "Global Leaderboard",
            "custom_songs" to "Custom Song List",
            "vocals_on" to "Original Vocals ON",
            "vocals_off" to "Vocal Cut active",
            "back" to "Back",
            "welcome" to "Welcome Back!",
            "enter_details" to "Enter your vocal credentials to begin",
            "create_account" to "Create Vocalist Profile",
            "save_locally" to "Save Locally",
            "save_cloud" to "Sync to Cloud",
            "empty_recordings" to "No recorded songs yet. Go sing and make history!",
            "empty_favorites" to "No favorite songs yet. Tap the heart icon to add!",
            "admin_intro" to "Manage karaoke tracks, upload backing tracks & synchronize lyrics.",
            "duration" to "Duration",
            "seconds" to "seconds",
            "original_vocals" to "Original Vocals",
            "instrumental_only" to "Instrumental Only"
        ),
        AppLanguage.FRENCH to mapOf(
            "app_name" to "Studio Karaoké",
            "search_hint" to "Rechercher titres, artistes, genres...",
            "sing" to "Chanter",
            "recordings" to "Enregistrements",
            "favorites" to "Favoris",
            "profile" to "Profil",
            "admin" to "Panneau Admin",
            "login" to "Connexion",
            "register" to "S'inscrire",
            "username" to "Nom d'utilisateur",
            "password" to "Mot de passe",
            "email" to "Adresse Email",
            "no_account" to "Pas de compte? Créer profil",
            "have_account" to "Déjà inscrit? Se connecter",
            "effects" to "Effets Vocaux",
            "vocal_removal" to "Coupe Vocale (Sim. IA)",
            "echo" to "Délai d'Écho",
            "reverb" to "Intensité Réverb",
            "bass_boost" to "Basses Puissantes",
            "mic_gain" to "Gain du Micro",
            "score" to "Score Vocal",
            "pitch_meter" to "Alignement de Hauteur",
            "play" to "Lecture",
            "pause" to "Pause",
            "speed" to "Contrôle de Vitesse",
            "pitch" to "Ajustement de Tonalité (Clé)",
            "save_recording" to "Enregistrer Mix Vocal",
            "share" to "Partager Enregistrement",
            "xp" to "XP Vocal",
            "level" to "Niveau Vocaliste",
            "achievements" to "Succès obtenus",
            "badges" to "Badges",
            "rank" to "Rang du Chanteur",
            "rank_bronze" to "Chanteur de Bronze",
            "rank_silver" to "Chanteur d'Argent",
            "rank_gold" to "Étoile d'Or",
            "rank_platinum" to "Artiste de Platine",
            "rank_legend" to "Légende du Karaoké",
            "add_song" to "Ajouter un titre",
            "song_title" to "Titre du morceau",
            "artist" to "Nom de l'artiste",
            "category" to "Catégorie / Genre",
            "lyrics_lrc" to "Paroles Synchronisées (Format LRC)",
            "lyrics_placeholder" to "[00:05.10]Première ligne de paroles\n[00:10.50]Ligne suivante de karaoké",
            "save" to "Sauvegarder",
            "history" to "Historique de chant",
            "syncing" to "Sauvegarde sur le Cloud...",
            "vocal_vol" to "Volume de la Voix",
            "music_vol" to "Volume de l'Instrument",
            "perfect" to "Parfait! 🔥",
            "great" to "Excellent! ✨",
            "good" to "Bien! 👍",
            "keep_it_up" to "Continuez ainsi! 🎤",
            "tap_to_sing" to "Appuyer pour Chanter",
            "settings" to "Paramètres",
            "logout" to "Déconnexion",
            "ranking" to "Classement Mondial",
            "custom_songs" to "Titres Personnalisés",
            "vocals_on" to "Voix d'origine active",
            "vocals_off" to "Filtre voix actif",
            "back" to "Retour",
            "welcome" to "Bon retour!",
            "enter_details" to "Entrez vos identifiants pour chanter",
            "create_account" to "Créer un profil vocaliste",
            "save_locally" to "Sauvegarder en local",
            "save_cloud" to "Synchro Cloud",
            "empty_recordings" to "Aucun enregistrement. Allez chanter votre premier tube!",
            "empty_favorites" to "Aucun favori. Touchez le cœur pour ajouter!",
            "admin_intro" to "Gérez les pistes, chargez des bandes sonores et synchronisez les paroles.",
            "duration" to "Durée",
            "seconds" to "secondes",
            "original_vocals" to "Voix Originales",
            "instrumental_only" to "Instrumental Uniquement"
        ),
        AppLanguage.ARABIC to mapOf(
            "app_name" to "استوديو كاريوكي",
            "search_hint" to "ابحث عن الأغاني، الفنانين، الفئات...",
            "sing" to "غنّي",
            "recordings" to "التسجيلات",
            "favorites" to "المفضلة",
            "profile" to "الملف الشخصي",
            "admin" to "لوحة التحكم",
            "login" to "تسجيل الدخول",
            "register" to "إنشاء حساب",
            "username" to "اسم المستخدم",
            "password" to "كلمة المرور",
            "email" to "البريد الإلكتروني",
            "no_account" to "ليس لديك حساب؟ سجل الآن",
            "have_account" to "لديك حساب بالفعل؟ سجل الدخول",
            "effects" to "المؤثرات الصوتية",
            "vocal_removal" to "عزل الصوت البشري (ذكاء اصطناعي)",
            "echo" to "تأخير الصدى",
            "reverb" to "قوة الارتداد",
            "bass_boost" to "تضخيم الباص",
            "mic_gain" to "حجم الميكروفون",
            "score" to "النتيجة الغنائية",
            "pitch_meter" to "مقياس دقة النغمة",
            "play" to "تشغيل",
            "pause" to "إيقاف مؤقت",
            "speed" to "التحكم بالسرعة",
            "pitch" to "طبقة الصوت (المفتاح)",
            "save_recording" to "حفظ المزيج الصوتي",
            "share" to "مشاركة الأداء",
            "xp" to "نقاط الصوت",
            "level" to "مستوى المغني",
            "achievements" to "الإنجازات والمكافآت",
            "badges" to "الشارات",
            "rank" to "رتبة المغني",
            "rank_bronze" to "مغني برونزي",
            "rank_silver" to "مغني فضي",
            "rank_gold" to "النجم الذهبي",
            "rank_platinum" to "الفنان البلاتيني",
            "rank_legend" to "أسطورة الكاريوكي",
            "add_song" to "إضافة أغنية مخصصة",
            "song_title" to "عنوان الأغنية",
            "artist" to "اسم الفنان",
            "category" to "الفئة أو النوع الموسيقي",
            "lyrics_lrc" to "الكلمات المتزامنة (تنسيق LRC)",
            "lyrics_placeholder" to "[00:05.10]السطر الأول من الكلمات المتزامنة\n[00:10.50]السطر التالي من كلمات الكاريوكي",
            "save" to "حفظ الأغنية",
            "history" to "سجل الغناء",
            "syncing" to "جاري المزامنة مع السحاب...",
            "vocal_vol" to "حجم صوت المغني",
            "music_vol" to "حجم صوت الموسيقى",
            "perfect" to "ممتاز! 🔥",
            "great" to "رائع! ✨",
            "good" to "جيد! 👍",
            "keep_it_up" to "واصل المحاولة! 🎤",
            "tap_to_sing" to "اضغط للغناء الآن",
            "settings" to "الإعدادات",
            "logout" to "تسجيل الخروج",
            "ranking" to "قائمة المتصدرين",
            "custom_songs" to "الأغاني المخصصة",
            "vocals_on" to "صوت المغني الأصلي مفعل",
            "vocals_off" to "عزل الصوت نشط",
            "back" to "رجوع",
            "welcome" to "مرحباً بعودتك!",
            "enter_details" to "أدخل بياناتك الصوتية للبدء",
            "create_account" to "إنشاء ملف مغني جديد",
            "save_locally" to "حفظ محلياً",
            "save_cloud" to "مزامنة سحابية",
            "empty_recordings" to "لا توجد تسجيلات حتى الآن. ابدأ الغناء الآن لصنع التاريخ!",
            "empty_favorites" to "قائمة المفضلة فارغة. اضغط على رمز القلب لإضافة الأغاني!",
            "admin_intro" to "إدارة مسارات الكاريوكي، ورفع الموسيقى الخلفية وتزامن الكلمات.",
            "duration" to "المدة",
            "seconds" to "ثانية",
            "original_vocals" to "الصوت الأصلي",
            "instrumental_only" to "الموسيقى فقط"
        )
    )

    fun translate(key: String, language: AppLanguage): String {
        return translations[language]?.get(key) ?: key
    }
}
